public enum TokenType {
    NUMBER, NEWLINE, OPERATOR, EOF, UNKNOWN,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, LEFT_PAREN, RIGHT_PAREN,
    LESS_THAN, MORE_THAN, EQUALS, NOT_EQUALS, LESS_EQUALS, MORE_EQUALS,
    WORD, NEW_VAR, ASSIGN
}